# Lenguaje principal
languageCode: en-us 

# Título del sitio
title: "Título"

# Tema que se usa
theme: "toha"
 
# Múltiples idiomas, aquí puedes definir qué idiomas tendrás en tu portafolio
 
languages:
  en:
    languageName: English
    weight: 1
  es:
    languageName: Español
    weight: 2
 
# Características de la navegación superior
markup:
  tableOfContents:
    startLevel: 2
    endLevel: 8
    ordered: false
 
# Habilitar uso de emojis
enableEmoji: true
 
# Parámetros del sitio
params:
  
  # Imagen de fondo
  background: "images/site/fondo4.jpg"
  
  # Poner un logo al sitio
  logo:
    main: /images/site/profile.png
    inverted: /images/site/profile.png
    favicon: /images/site/profile.png
 
 # Habilitar tema oscuro
  darkMode:
    provider: darkreader
    enable: true
    default: system
 
  # Link del repositorio de Github
  gitRepo: https://github.com/hugo-toha/hugo-toha.github.io
 
  # Habilitar la parte de Blog
  enableBlogPost: false
 
  # Habilitar Tabla de Contenidos
  enableTOC: true
 
  # Deshabilitar Newsletter
  newsletter:
    enable: false
 
  # Poner banderas de múltiples idiomas
  flagOverwrites:
  - languageCode: en
    countryCode: us
  - languageCode: es
    countryCode: mx
 


